[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "vllm-plugin-signature-enforcement"
dynamic = ["version"]
description = "A vLLM plugin for signature enforcement on AI models and LoRA adapters"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Stefan Berger", email = "stefanb@us.ibm.com" }
]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Security",
  "Topic :: Security :: Cryptography",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Typing :: Typed",
]
dependencies = [
  "jsonschema",
  "model-signing @ git+https://github.com/sigstore/model-transparency",
  "regex",
  "types-jsonschema",
  "typing_extensions",
]
requires-python = ">=3.9"
keywords = [
  "machine learning",
  "artificial intelligence",
  "model signing",
  "AI security",
  "ML security",
  "AI supply chain security",
  "ML supply chain security",
]

[project.entry-points."vllm.general_plugins"]
signature_enforcement = "vllm_plugin_signature_enforcement.signature_enforcement:register_model_validation_plugin"

[project.urls]

[tool.hatch.version]
path = "src/vllm_plugin_signature_enforcement/__init__.py"

[tool.hatch.build]
packages = ["src/vllm_plugin_signature_enforcement"]

[tool.hatch.envs.hatch-test]
installer = "pip"
parallel = true
randomize = true
extra-args = ["-m", "not integration"]

[tool.hatch.metadata] 
allow-direct-references = true

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.9", "3.10", "3.11", "3.12", "3.13"]

[tool.hatch.envs.bench]
description = """Custom environment for running benchmarks.
Use `hatch run +py=3... bench:generate ${args}` to generate test models.
Use `hatch run +py=3... bench:serialize ${args}` to benchmark serialization code.
Use `hatch run +py=3... bench:hash ${args}` to benchmark hashing code.
Use `hatch run +py=3... bench:chunk ${args}` to benchmark the chunk size parameter.
"""
extra-dependencies = [
]

[[tool.hatch.envs.bench.matrix]]
python = ["3.9", "3.10", "3.11", "3.12", "3.13"]

[tool.hatch.envs.type.scripts]
check = "pytype -k -j auto src tests benchmarks"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib"
]

[tool.ruff]
line-length = 80

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"
skip-magic-trailing-comma = true

[tool.ruff.lint]
select = ["B", "D", "E", "F", "I", "N", "PLC", "PLE", "PT", "SIM", "UP", "W"]
ignore = [
  # TODO: selectively enable back most of these in subsequent PRs
  "B024", "D100", "D101", "D102", "D103", "D104", "D105", "D107", "D205", "D415",
  # Unnecessary arguments can help with clarity
  "UP012", "UP015", "N802"
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false

[tool.ruff.lint.isort]
force-single-line = true
force-sort-within-sections = true
lines-after-imports = 2
single-line-exclusions = ["collections.abc", "typing"]

[tool.ruff.lint.pep8-naming]
ignore-names = ["TestOneInput"]

[tool.ruff.lint.pydocstyle]
convention = "google"
